from omen.scenario.situation_analyzer import situation_artifact_to_markdown


def test_situation_markdown_renders_strategic_brief_sections() -> None:
    payload = {
        "id": "nokia-elop-2010",
        "version": "0.1.0",
        "context": {
            "title": "Nokia strategic pivot",
            "core_question": "Should Nokia keep platform control or move fast via alliance?",
            "current_state": "Legacy platform pressure is increasing while transition speed is low.",
            "core_dilemma": "Platform autonomy vs near-term survivability",
            "key_decision_point": "Choose internal transition vs external ecosystem alliance.",
            "target_outcomes": ["Stabilize market share", "Improve transition speed"],
            "hard_constraints": ["Legacy stack inertia", "Coordination overhead"],
            "known_unknowns": ["Hidden veto nodes"],
        },
        "signals": [
            {"id": "s1", "name": "Android ecosystem expansion"},
            {"id": "s2", "name": "Internal reallocation drag"},
        ],
        "uncertainty_space": {
            "overall_confidence": 0.45,
            "high_leverage_unknowns": ["Board-level alignment risk"],
            "assumptions_explicit": [],
        },
        "source_meta": {
            "source_path": "cases/situations/nokia-elop-2010.md",
            "generated_at": "2026-04-05T12:00:00",
        },
    }

    rendered = situation_artifact_to_markdown(payload)

    assert "# 📊 Strategic Situation Brief" in rendered
    assert "## 1. 🎭 Current State" in rendered
    assert "## 2. 🎯 Target Outcomes" in rendered
    assert "## 3. ⚔️ Core Question" in rendered
    assert "## 4. ⚖️ Dilemma" in rendered
    assert "## 5. 🎯 Key Decision Point" in rendered
    assert "## 6. 🧱 Hard Constraints" in rendered
    assert "## 7. ⚠️ Known Unknowns" in rendered
    assert "## 8. 📉 Confidence & Uncertainty" in rendered
    assert "**Executive Summary:**" in rendered
    assert "Platform autonomy vs near-term survivability" in rendered
    assert "Hidden veto nodes" in rendered
    assert "Overall Confidence" in rendered
    assert "## Omen reminder" in rendered
    assert "generated by Omen AI" in rendered
    assert "Next Step:" in rendered
    assert "`omen scenario --situation <situation_json_path>`" in rendered
