import omen.ingest.reportor.situation_brief as situation_brief_renderer

from omen.ingest.synthesizer.builders.situation import situation_artifact_to_markdown


def test_situation_markdown_renders_strategic_brief_sections(monkeypatch) -> None:
    def _fake_invoke(*, _config_path: str, user_prompt: str, _system_prompt: str | None = None) -> str:
        json_payload = user_prompt.split("Situation data (JSON):", 1)[1]
        assert '"risk_confidence": 0.4' in user_prompt
        assert '"known_unknowns": [' in user_prompt
        assert '"overall_confidence"' not in json_payload
        assert '"confidence_overall"' not in json_payload
        assert '"assumptions_explicit"' not in json_payload

        return """# 📝 Strategic Situation Brief

**ID:** nokia-elop-2010
**Version:** 0.1.0 (Phase 1)
**Core Topic:** Nokia strategic pivot
**Source:** cases/situations/nokia-elop-2010.md
**Generated:** 2026-04-05T12:00:00

**Executive Summary:** The current review indicates a material strategic inflection point. Primary dilemma: Platform autonomy vs near-term survivability.

---

## 1. 🎭 Current State
Legacy platform pressure is increasing while transition speed is low.

## 2. 🎯 Target Outcomes
- Stabilize market share
- Improve transition speed

## 3. ⚔️ Core Question
Should Nokia keep platform control or move fast via alliance?

## 4. 🧱 Dilemma
> Platform autonomy vs near-term survivability

## 5. ⚖️ Key Decision Point
Choose internal transition vs external ecosystem alliance.

## 6. 🛑 Hard Constraints
- Legacy stack inertia
- Coordination overhead

## 7. ⚠️ Known Unknowns
- Hidden veto nodes

## 8. 📉 Confidence & Uncertainty
Risk Confidence: 0.4 (low).
Known Unknown exposure remains material, especially around hidden veto nodes.

---

### 📌 Omen reminder

The situation brief is generated by Omen LLM-based analysis of the source.

**Status:** Phase 1 Complete (Context Extraction)
**Next Step:** Run `omen scenario --situation <situation_json_path>` to generate deterministic A/B/C scenarios.
"""

    monkeypatch.setattr(situation_brief_renderer, "invoke_text_prompt", _fake_invoke)

    payload = {
        "id": "nokia-elop-2010",
        "version": "0.1.0",
        "context": {
            "title": "Nokia strategic pivot",
            "core_question": "Should Nokia keep platform control or move fast via alliance?",
            "current_state": "Legacy platform pressure is increasing while transition speed is low.",
            "core_dilemma": "Platform autonomy vs near-term survivability",
            "key_decision_point": "Choose internal transition vs external ecosystem alliance.",
            "target_outcomes": ["Stabilize market share", "Improve transition speed"],
            "hard_constraints": ["Legacy stack inertia", "Coordination overhead"],
            "known_unknowns": ["Hidden veto nodes"],
        },
        "signals": [
            {"id": "s1", "name": "Android ecosystem expansion"},
            {"id": "s2", "name": "Internal reallocation drag"},
        ],
        "uncertainty_space": {
            "confidence_risk": 0.4,
            "overall_confidence": 0.45,
            "confidence_overall": 0.7,
            "high_leverage_unknowns": ["Board-level alignment risk"],
            "assumptions_explicit": [],
        },
        "source_meta": {
            "source_path": "cases/situations/nokia-elop-2010.md",
            "generated_at": "2026-04-05T12:00:00",
        },
    }

    rendered = situation_artifact_to_markdown(payload)

    assert "# 📝 Strategic Situation Brief" in rendered
    assert "## 1. 🎭 Current State" in rendered
    assert "## 2. 🎯 Target Outcomes" in rendered
    assert "## 3. ⚔️ Core Question" in rendered
    assert "## 4. 🧱 Dilemma" in rendered
    assert "## 5. ⚖️ Key Decision Point" in rendered
    assert "## 6. 🛑 Hard Constraints" in rendered
    assert "## 7. ⚠️ Known Unknowns" in rendered
    assert "## 8. 📉 Confidence & Uncertainty" in rendered
    assert "**Executive Summary:**" in rendered
    assert "Platform autonomy vs near-term survivability" in rendered
    assert "Hidden veto nodes" in rendered
    assert "Risk Confidence" in rendered
    assert "Overall Confidence" not in rendered
    assert "### 📌 Omen reminder" in rendered
    assert "generated by Omen LLM-based analysis of the source" in rendered
    assert "Next Step:" in rendered
    assert "`omen scenario --situation <situation_json_path>`" in rendered
