from pathlib import Path
import omen.ingest.reporter.markdown as markdown_reporter


def test_situation_markdown_renders_strategic_brief_sections(monkeypatch) -> None:
    def _fake_invoke(*, user_prompt: str, system_prompt: str | None = None, config_path: str | None = None) -> str:
        _ = config_path, system_prompt
        json_payload = user_prompt.split("Situation data (JSON):", 1)[1]
        assert '"risk_confidence": 0.4' in user_prompt
        assert '"known_unknowns": [' in user_prompt
        assert '"overall_confidence"' not in json_payload
        assert '"confidence_overall"' not in json_payload
        assert '"assumptions_explicit"' not in json_payload

        return """# 📝 Strategic Situation Brief

**ID:** nokia-elop-2010
**Version:** 0.1.0 (Phase 1)
**Core Topic:** Nokia strategic pivot
**Source:** cases/situations/nokia-elop-2010.md
**Generated:** 2026-04-05T12:00:00

**Executive Summary:** The current review indicates a material strategic inflection point. Primary dilemma: Platform autonomy vs near-term survivability.

---

## 1. 🎭 Current State
Legacy platform pressure is increasing while transition speed is low.

## 2. 🎯 Target Outcomes
- Stabilize market share
- Improve transition speed

## 3. ⚔️ Core Question
Should Nokia keep platform control or move fast via alliance?

## 4. 🧱 Dilemma
> Platform autonomy vs near-term survivability

## 5. ⚖️ Key Decision Point
Choose internal transition vs external ecosystem alliance.

## 6. 🛑 Hard Constraints
- Legacy stack inertia
- Coordination overhead

## 7. ⚠️ Known Unknowns
- Hidden veto nodes

## 8. 📉 Confidence & Uncertainty
Risk Confidence: 0.4 (low).
Known Unknown exposure remains material, especially around hidden veto nodes.

---

### 📌 Omen reminder

The situation brief is generated by Omen LLM-based analysis of the source.

**Status:** Phase 1 Complete (Context Extraction)
**Next Step:** Run `omen scenario --situation <situation_json_path>` to generate deterministic A/B/C scenarios.
"""

    monkeypatch.setattr(markdown_reporter, "invoke_text_prompt", _fake_invoke)

    payload = {
        "id": "nokia-elop-2010",
        "version": "0.1.0",
        "context": {
            "title": "Nokia strategic pivot",
            "core_question": "Should Nokia keep platform control or move fast via alliance?",
            "current_state": "Legacy platform pressure is increasing while transition speed is low.",
            "core_dilemma": "Platform autonomy vs near-term survivability",
            "key_decision_point": "Choose internal transition vs external ecosystem alliance.",
            "target_outcomes": ["Stabilize market share", "Improve transition speed"],
            "hard_constraints": ["Legacy stack inertia", "Coordination overhead"],
            "known_unknowns": ["Hidden veto nodes"],
        },
        "signals": [
            {"id": "s1", "name": "Android ecosystem expansion"},
            {"id": "s2", "name": "Internal reallocation drag"},
        ],
        "uncertainty_space": {
            "confidence_risk": 0.4,
            "overall_confidence": 0.45,
            "confidence_overall": 0.7,
            "high_leverage_unknowns": ["Board-level alignment risk"],
            "assumptions_explicit": [],
        },
        "source_meta": {
            "source_path": "cases/situations/nokia-elop-2010.md",
            "generated_at": "2026-04-05T12:00:00",
        },
    }

    rendered = markdown_reporter.render_situation_brief(payload)

    assert "# 📝 Strategic Situation Brief" in rendered
    assert "## 1. 🎭 Current State" in rendered
    assert "## 2. 🎯 Target Outcomes" in rendered
    assert "## 3. ⚔️ Core Question" in rendered
    assert "## 4. 🧱 Dilemma" in rendered
    assert "## 5. ⚖️ Key Decision Point" in rendered
    assert "## 6. 🛑 Hard Constraints" in rendered
    assert "## 7. ⚠️ Known Unknowns" in rendered
    assert "## 8. 📉 Confidence & Uncertainty" in rendered
    assert "**Executive Summary:**" in rendered
    assert "Platform autonomy vs near-term survivability" in rendered
    assert "Hidden veto nodes" in rendered
    assert "Risk Confidence" in rendered
    assert "Overall Confidence" not in rendered
    assert "### 📌 Omen reminder" in rendered
    assert "generated by Omen LLM-based analysis of the source" in rendered
    assert "Next Step:" in rendered
    assert "`omen scenario --situation <situation_json_path>`" in rendered


def test_save_situation_brief_writes_file(monkeypatch, tmp_path: Path) -> None:
    payload = {
        "id": "nokia-elop-2010",
        "version": "0.1.0",
        "context": {
            "title": "Nokia strategic pivot",
            "core_question": "Q",
            "current_state": "S",
            "core_dilemma": "D",
            "key_decision_point": "K",
            "target_outcomes": ["T"],
            "hard_constraints": ["H"],
            "known_unknowns": ["U"],
        },
        "uncertainty_space": {"confidence_risk": 0.4},
        "source_meta": {
            "source_path": "cases/situations/nokia-elop-2010.md",
            "generated_at": "2026-04-05T12:00:00",
        },
    }

    monkeypatch.setattr(
        markdown_reporter,
        "render_situation_brief",
        lambda situation: "# Strategic Situation Brief\n\nSaved output\n",
    )

    output_path = tmp_path / "reports" / "situation.md"
    written = markdown_reporter.save_situation_brief(output_path, payload)

    assert written == output_path
    assert output_path.exists()
    assert output_path.read_text(encoding="utf-8") == "# Strategic Situation Brief\n\nSaved output\n"


def test_render_scenario_ontology_markdown_contains_sections() -> None:
    ontology = {
        "derived_from_situation_id": "sap_reltio_acquisition",
        "pack_id": "sap_v1",
        "pack_version": "1.0.0",
        "ontology_version": "scenario_ontology_v1",
        "source_meta": {
            "source_path": "cases/situations/sap_reltio_acquisition.md",
            "generated_at": "2026-04-10T09:00:00",
        },
        "scenarios": [
            {
                "scenario_key": "A",
                "title": "Aggressive expansion",
                "goal": "Expand platform reach",
                "target": "Enterprise segment",
                "objective": "Increase adoption",
                "variables": [{"name": "go_to_market", "type": "strategy"}],
                "constraints": ["Budget limit"],
                "tradeoff_pressure": ["Speed vs quality"],
                "resistance_assumptions": {
                    "structural_conflict": 0.4,
                    "resource_reallocation_drag": 0.5,
                    "cultural_misalignment": 0.3,
                    "veto_node_intensity": 0.2,
                    "aggregate_resistance": 0.35,
                    "assumption_rationale": ["Incumbent teams protect current workflows"],
                },
                "modeling_notes": ["Assumes higher sales activation capacity"],
            }
        ],
    }

    rendered = markdown_reporter.render_scenario_ontology_markdown(ontology)

    assert "# Scenario Ontology: sap_reltio_acquisition" in rendered
    assert "- pack_id: sap_v1" in rendered
    assert "## Scenario A: Aggressive expansion" in rendered
    assert "- constraints:" in rendered
    assert "- tradeoff_pressure:" in rendered
    assert "- resistance_assumptions:" in rendered
